/*
Blazium API

Testing LobbyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/blazium-engine/blazium-signal-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_LobbyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LobbyAPIService LobbyCreate", func(t *testing.T) {
		apiLobbyCreateRequest := apiClient.LobbyAPI.LobbyCreate(context.Background())
		apiLobbyCreateRequest.LobbyCreateRequest(
			&openapiclient.LobbyCreateRequest{
				Name: "name_example",
			})

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
