/*
Blazium API

API for managing lobbies and game sessions.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LobbyCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LobbyCreatedResponse{}

// LobbyCreatedResponse struct for LobbyCreatedResponse
type LobbyCreatedResponse struct {
	// The command returned by the server.
	Command *string `json:"command,omitempty"`
	// Informational message about the operation.
	Message *string `json:"message,omitempty"`
	Data *LobbyCreatedResponseData `json:"data,omitempty"`
}

// NewLobbyCreatedResponse instantiates a new LobbyCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLobbyCreatedResponse() *LobbyCreatedResponse {
	this := LobbyCreatedResponse{}
	return &this
}

// NewLobbyCreatedResponseWithDefaults instantiates a new LobbyCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLobbyCreatedResponseWithDefaults() *LobbyCreatedResponse {
	this := LobbyCreatedResponse{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *LobbyCreatedResponse) GetCommand() string {
	if o == nil || IsNil(o.Command) {
		var ret string
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LobbyCreatedResponse) GetCommandOk() (*string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *LobbyCreatedResponse) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given string and assigns it to the Command field.
func (o *LobbyCreatedResponse) SetCommand(v string) {
	o.Command = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *LobbyCreatedResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LobbyCreatedResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *LobbyCreatedResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *LobbyCreatedResponse) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LobbyCreatedResponse) GetData() LobbyCreatedResponseData {
	if o == nil || IsNil(o.Data) {
		var ret LobbyCreatedResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LobbyCreatedResponse) GetDataOk() (*LobbyCreatedResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LobbyCreatedResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given LobbyCreatedResponseData and assigns it to the Data field.
func (o *LobbyCreatedResponse) SetData(v LobbyCreatedResponseData) {
	o.Data = &v
}

func (o LobbyCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LobbyCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableLobbyCreatedResponse struct {
	value *LobbyCreatedResponse
	isSet bool
}

func (v NullableLobbyCreatedResponse) Get() *LobbyCreatedResponse {
	return v.value
}

func (v *NullableLobbyCreatedResponse) Set(val *LobbyCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLobbyCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLobbyCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLobbyCreatedResponse(val *LobbyCreatedResponse) *NullableLobbyCreatedResponse {
	return &NullableLobbyCreatedResponse{value: val, isSet: true}
}

func (v NullableLobbyCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLobbyCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


